#dev properties
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: aXia0507
    username: root
    driver-class-name: com.mysql.jdbc.Driver

#端口配置
server:
  port: 80

#mybatis配置
#mybatis:
#  mapper-locations: classpath*:/com/jzp/dao/mybatis/**Mapping.xml

#logging:
#  config: classpath:logback.xml
